name: Release
"on":
    push:
        tags: v[0-9]+.[0-9]+.[0-9]+
jobs:
    build:
        name: 'Build: ${{matrix.rid}}'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                rid:
                    - linux-x64
                    - linux-arm64
                    - osx-x64
                    - osx-arm64
                    - win-x64
                    - win-arm64
        steps:
            - name: clone repository
              uses: actions/checkout@v3
            - name: install dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.x
            - name: change project name
              run: mv -f ./project.csproj ./spfw.csproj
            - name: build project
              run: dotnet publish -r ${{matrix.rid}} -p:FileVersion=`echo '${{github.ref_name}}' | sed 's/v//'`.0
            - name: archive binary
              run: tar c -z -f ./spfw-${{matrix.rid}}.tgz -C ./bin/Release/${{matrix.rid}}/publish ./
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: ${{matrix.rid}}
                path: ./spfw-${{matrix.rid}}.tgz
    release:
        name: 'Release: ${{github.ref_name}}'
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: download artifact
              uses: actions/download-artifact@v3
            - name: dispatch release
              uses: softprops/action-gh-release@v1
              with:
                generate_release_notes: true
                files: |-
                    ./linux-x64/spfw-linux-x64.tgz
                    ./linux-arm64/spfw-linux-arm64.tgz
                    ./osx-x64/spfw-osx-x64.tgz
                    ./osx-arm64/spfw-osx-arm64.tgz
                    ./win-x64/spfw-win-x64.tgz
                    ./win-arm64/spfw-win-arm64.tgz